### PR TITLE
Update gjs

### PR DESCRIPTION
**Pull request by danigm**
https://phabricator.endlessm.com/T26332

### CODE REVIEW

**Review by ptomato — APPROVED** [review]
This is fine with me, I did mention in the Phabricator ticket that we will do the meson port differently upstream with meson 0.50, but I have no problem with merging this one downstream for now. The other commits all come directly from upstream.

**Review by wjt — DISMISSED** [review]
You will need to either drop the "move to meson" commit, or update the Debian packaging in `debian/`. For example, depending on and using `dh-autoreconf` will not be very useful when the autotools stuff is gone, and you probably need to add a dependency on meson.

**Comment by wjt** [comment]
Oh, maybe I need to add a webhook to tell Jenkins about this repo.

**Comment by wjt** [comment]
retest this please

**Comment by wjt** [comment]
I also pushed a `Version_2.2.1` tag. I tested with my change and it builds successfully on both Jenkins, and on OBS https://obs-master.endlessm-sf.com/package/show/home:wjt:branches:eos:master:endless/jasmine-gjs . We can merge this after https://github.com/endlessm/eos-build/pull/953

**Pull request merged**
